---
title: "R Bootcamp, Module 0: Recruit Processing"
date: "January 2018 (RPI)"
author:
- "Created by: Chris Paciorek (UC Berkeley)"
- "Edited by: John Erickson (RPI IDEA)"
output: slidy_presentation
---

# A few administrative items

## Where to find stuff

* Github site for our version of these materials:   [https://github.com/TheRensselaerIDEA/r-bootcamp-2018-rpi](https://github.com/TheRensselaerIDEA/r-bootcamp-2018-rpi)
* Github site for Berkeley's original version:   
[https://github.com/berkeley-scf/r-bootcamp-2017](https://github.com/berkeley-scf/r-bootcamp-2017)
* You can 'clone' the github repositories or get the individual files from Github. 

If you have an administrative question, email idea-r-bootcamp@cs.lists.rpi.edu 

# How we'll operate

* The Bootcamp is organized in modules, each of which will be a combination of lecture/demo presentation concluded by a 'breakout' session in which you'll work on a variety of problems of different levels of difficulty. 

* Our idea (hope?) is for each person to find problems that challenge them but are not too hard. Solutions to the breakout problems will be presented before the start of the next module. 

* Many of the modules will use a common dataset as an example on which to carry out various operations. 
    + We'll focus on a dataset of on-time information for US airline flights, 1987-2008 provided by the US government's Bureau of Transportation Statistics. This dataset is available in its entirety [here](http://stat-computing.org/dataexpo/2009/the-data.html). 
    + This dataset is about 3.5 Gb compressed, so we'll work with a subset of just flights departing from SFO for 2005-2008, available in the Github repository as *airline.csv*.
    + Note that this is the full population of such flights -- We'll fit some statistical models but the interpretation is tricky as we are not working with a sample from a well-defined population.
    + There's also a smaller subsample of the SFO flights in *airlineSubsample.csv* - you can use that in place of *airline.csv* if *airline.csv* is taking a while to load into R on your machine.

# How we'll operate (2)

* Helpers will be available to help answer any questions you have (just wave to one of them), or feel free to just ask the presenter during the presentation. 
* We have set up a Slack channel for Bootcamp-related chats; see []()
* Feel free to type in a question there and one of the helps will answer the question. If you see a question and know the answer, help us out by answering it yourself or adding your thoughts. 


# Getting the most out of the Bootcamp

Please:

* Try out the code as we walk through it
* Keep your eyes open! -- We'll illustrate a lot of syntax and concepts by example
* Try to guess what the syntax means in cases we haven't yet seen that syntax
* Play with it and try variations and try to break it and see what happens
* Tell us if something interesting happens as you experiment, or post a comment in the chat room
* Ask questions of the presenter, the helpers, and in the Slack channel

*This is a bootcamp.* So there may be some pain involved! If you find yourself not following everything, that's ok. You may miss some details, but try to follow the basics and the big picture. 

# A few additional thoughts 

* We want to expose you to a lot of tools and ideas that you can come back to when you need them and when you have time for more depth.
* Our aim is not to show you how to use specific statistical methods or analysis techniques. My goal is to get you up to speed generally in R.
* It can be hard to absorb everything in such a concentrated situation. Hopefully the material presented will be useful to you over the longer-term as you do more work with R.

# RStudio and R Markdown

+ We'll present most of the material from within RStudio, using R Markdown documents with embedded R code. 
+ R Markdown is an extension to the Markdown markup language that makes it easy to write HTML in a simple plain text format.  This allows us to both run the R code directly as well as compile on-the-fly to an HTML file that can be used for presentation. 
+ All source files will be available on our  [Github](https://github.com/TheRensselaerIDEA/r-bootcamp-2018-rpi)

Note: The files named *moduleX_blah_slides.html* have individual slides, while the files named *moduleX_blah.html* have the same content but all on one page.

Warning: in some cases the processing of the R code in the R Markdown is screwy and the slides have error messages that do not occur if you just run the code directly in R or RStudio. 

# Using Github to get the documents (not required!)

To download the files from Github, you can do the following. 

## Within RStudio

Within RStudio go to `File->New Project->Version Control->Git` and enter:

+ "Repository URL": `https://github.com/TheRensselaerIDEA/r-bootcamp-2018-rpi`
+ "Project Directory Name": `r-bootcamp-2018` (or something else of your choosing)
+ "Directory": `~/Desktop` (or somewhere of your choosing)

Then to update from the repository to get any changes we've made, you can select (from within RStudio):
`Tools -> Version Control -> Pull Branches`

or from the Environment/History/Git window, click on the Git tab and then on the blue down arrow.

Be warned that you probably do not want to make your own notes or changes to the files we are providing. Because if you do, and you then do a "Git Pull" to update the materials, you'll have to deal with the conflict between your local version and our version. You probably will want to make a personal copy of such files in another directory or by making copies of files with new names.

## From a Mac/Linux terminal window

Run the following commands:

- `cd /directory/where/you/want/repository/located`
- `git clone https://github.com/TheRensselaerIDEA/r-bootcamp-2018-rpi`

Then to update from the repository to get any changes we've made:

- `cd /directory/where/you/put/the/repository/r-bootcamp-2018`
- `git pull`

## As a zip file

If you don't want to bother using Git or have problems, simply download a zip file with all the material from [https://codeload.github.com/TheRensselaerIDEA/r-bootcamp-2018-rpi/zip/master.zip](https://codeload.github.com/TheRensselaerIDEA/r-bootcamp-2018-rpi/zip/master.zip).

# What is R?

+ R is an Open Source (and freely available) environment for statistical computing and graphics
+ It is a full-featured programming language, in particular a scripting language (with similarities to Matlab and Python)
+ It can be run interactively or as a batch/background job
+ R is being actively developed with ongoing updates/new releases
+ R has a variety of built-in as well as community-provided packages that extend its functionality with code and data; see [CRAN](https://www.cran.r-project.org/web/packages/index.html) for the thousands of add-on packages
+ It is freely-available and modifiable 
+ Available for Windows, Mac OS X, and [Linux](http://dilbert.com/strips/comic/1995-06-24/)


# Modes of using R

+ Using the RStudio GUI, an 'integrated development environment'
+ From the command line in a Linux/Mac terminal window
+ Running an R script in the background on a Linux/Mac machine (Windows?)
+ Using the Windows/Mac GUIs


# Starting R and RStudio

The pieces of an R session include:

- The R console
- Scripts containing your code
- Help files
- Graphics windows
- Workspace containing your objects, which hold data and information

RStudio provides an integrated development environment in which all of these pieces are in a single application and tightly integrated, with a built-in editor for your code/scripts. 

# Why R?

1. R is widely used (statisticians, scientists, social scientists) and has the widest statistical functionality of any software
2. Users add functionality via packages all the time
3. R is free and available on all major platforms
4. As a scripting language, R is very powerful, flexible, and easy to use
5. As a scripting language, R allows for reproducibility and automating tasks
6. As a language, R can do essentially anything
7. Wide usage helps to improve quality and reduce bugs
8. R can interact with other software, databases, the operating system, the web, etc.
9. R is built on C and can call user-written and external C code and packages (in particular, see the **Rcpp** R package)

# Why Not R?

* Other software is better than R at various tasks
    
* E.g., [Python](http://imgs.xkcd.com/comics/python.png) is very good for text manipulation, interacting with the operating system, and as a glue for tying together various applications/software in a workflow
* R can be much slower than compiled languages
    + but is often quite fast with good coding practices!
* R's packages are only as good as the person who wrote them; no explicit quality control
* R is a sprawling and (somewhat) un-standardized ecosystem

# What are my other options? Get me out of here!

- Python
- MATLAB/Octave
- Julia
- C/C++
- SAS
- Stata

# Our hidden agenda

In addition to learning some R, this workshop will expose you to a way of thinking about doing your computational work. 

The building blocks of **scientific computing** include:

+ scripting
+ reproducibility
+ automating repetitive tasks
+ version control (note our basic use of Git)

# The Legal Stuff

- Most of this material is a clone of Chris Paciorek's [R Bootcamp](https://github.com/berkeley-scf/r-bootcamp-2017) (UC Berkeley)
- Some of this material was drawn from Jared Knowles' [R bootcamp](http://jaredknowles.com/r-bootcamp/url).
- Contributions from Kellie Ottoboni, Nima Hejazi, Rochelle Terman, Chris Krogslund, and Jarrod Millman (UC Berkeley)
- Readers are free to use, modify and redistribute any of this material with or without attribution, but if you use chunks of material, the previous authors would appreciate a call-out.

# Next Module

* [Module 0: Induction Slides](module0_induction_slides.html)
* [Module 1: Basics Slides](module1_basics_slides.html)
* [Module 2: Managingr Slides](module2_managingR_slides.html)
* [Module 3: Data Slides](module3_data_slides.html)
* [Module 4: Calc Slides](module4_calc_slides.html)
* [Module 5: Tidyverse Slides](module5_tidyverse_slides.html)
* [Module 6: Programming Slides](module6_programming_slides.html)
* [Module 7: Analysis Slides](module7_analysis_slides.html)
* [Module 8: Graphics Slides](module8_graphics_slides.html)
* [Module 9: Workflows Slides](module9_workflows_slides.html)
* [Module 10: Advanced Slides](module10_advanced_slides.html)
* [Module 11: Next Slides](module11_next_slides.html)

