---
title: "R Bootcamp, Module 11: </br>Next Steps"
date: "January 2018 (RPI)"
author:
- "Created by: Chris Paciorek (UC Berkeley)"
- "Edited by: John Erickson (RPI IDEA)"
output: slidy_presentation
---

```{r chunksetup, include=FALSE} 
# include any code here you don't want to show up in the document,
# e.g. package and dataset loading
```

# The R Way

As we've seen, R is powerful, flexible, and wide-ranging. 

It's also sprawling, disorganized, and use-at-your-own risk. 

Base packages, widely-used packages and packages by frequent R contributors are more trustworthy. 

# Some of the 'features' of R

* R is inconsistent in its naming conventions: Some functions are *camelCase*; others are *dot.separated*; others *use_underscores*. For programmers used to OOP, the use of dots is maddening.
* Multiple OOP paradigms and OOP is not as clean or full-featured as other languages
* R has multiple graphics packages that different functions use for default plot construction (`base`, `grid`, `lattice`, and `ggplot2`)
* R has multiple packages and functions to do the same analysis
* R obscures some of what happens behind the scenes in a way that can be confusing and lead to errors: type coercion/casting, recycling, etc.

Any other things that you found frustrating and don't think are well-designed?


# R tutorials, materials, and assistance

Some of this material was borrowed/modified from [Jared Knowles' bootcamp](http://jaredknowles.com/r-bootcamp/)

CRAN has [manuals](https://cran.r-project.org/manuals.html) and [contributed learning material](https://cran.r-project.org/other-docs.html).

The SCF has a series of [hands-on tutorials](http://statistics.berkeley.edu/computing/training/tutorials) on related topics, some focused on topics in R, others on topics in UNIX/bash, and others on topics in managing workflows and reproducible research.

[D-Lab](http://dlab.berkeley.edu) holds workshops on R and other topics, as well as having drop-in office hours. 

Talk to The Rensselaer IDEA if you need consulting in data analytics, including use of the IDEA Cluster for research, classes, etc. 

Various online tutorials/courses are offered by [DataCamp](https://www.datacamp.com/), [Software Carpentry](http://swcarpentry.github.io/r-novice-inflammation/), [Coursera](https://www.coursera.org/course/rprog), and [Leada](https://www.teamleada.com/courses).  The DataCamp Introduction to R and Intermediate R courses are free and look pretty good to me.

# Some good books
 
R in general:

* Adler, Joseph; R in a Nutshell (available electronically through OskiCat: [http://uclibs.org/PID/151634](http://uclibs.org/PID/151634)) (hands-on)
* Wickham, Hadley; R for Data Science. 
* Wickham, Hadley; Advanced R. [http://adv-r.had.co.nz](http://adv-r.had.co.nz) (good coverage of advanced topics in the R language)
* Chambers, John; Software for Data Analysis: Programming with R (available electronically through OskiCat: [http://dx.doi.org/10.1007/978-0-387-75936-4](http://dx.doi.org/10.1007/978-0-387-75936-4)) (More conceptual/theoretical)

Specific aspects of R:

* Xie, Yihui; Dynamic documents with R and knitr.
* Nolan, Deborah and and Duncan Temple Lang; XML and Web Technologies for Data Sciences with R (available electronically through OskiCat: [http://dx.doi.org/10.1007/978-1-4614-7900-0](http://dx.doi.org/10.1007/978-1-4614-7900-0))
* Murrell, Paul; R Graphics, 2nd ed. [http://www.stat.auckland.ac.nz/\~paul/RG2e](http://www.stat.auckland.ac.nz/\~paul/RG2e/)
* Murrell, Paul; Introduction to Data Technologies. [http://www.stat.auckland.ac.nz/\~paul/ItDT/](http://www.stat.auckland.ac.nz/\~paul/ItDT/)

# Thanks!  

* The Rensselaer IDEA Team
* The UC Berkeley Team 
* The R Universe

# Next Module

* [Module 0: Induction Slides](module0_induction_slides.html)
* [Module 1: Basics Slides](module1_basics_slides.html)
* [Module 2: Managingr Slides](module2_managingR_slides.html)
* [Module 3: Data Slides](module3_data_slides.html)
* [Module 4: Calc Slides](module4_calc_slides.html)
* [Module 5: Tidyverse Slides](module5_tidyverse_slides.html)
* [Module 6: Programming Slides](module6_programming_slides.html)
* [Module 7: Analysis Slides](module7_analysis_slides.html)
* [Module 8: Graphics Slides](module8_graphics_slides.html)
* [Module 9: Workflows Slides](module9_workflows_slides.html)
* [Module 10: Advanced Slides](module10_advanced_slides.html)
* [Module 11: Next Slides](module11_next_slides.html)
